version: '3'
services:
  web:
    image: todolist/simple-website
    build: .
    ports:
      - "4000:80"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://tuan:tuanpham123@db:5432/todolist
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: tuan
      POSTGRES_PASSWORD: tuanpham123
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
