version: '3'
services:
  web:
    image: todolist/simple-website
    build: .
    ports:
      - "4000:80"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://tuan:tuanpham123@db:5432/todolist
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: tuan
      POSTGRES_PASSWORD: tuanpham123
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tuan -d todolist"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
